# Generated by Django 4.1.2 on 2023-06-30 10:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='id',
        ),
        migrations.RemoveField(
            model_name='tipocomida',
            name='id',
        ),
        migrations.RemoveField(
            model_name='tipocomida',
            name='nombre',
        ),
        migrations.AddField(
            model_name='producto',
            name='activo',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='tipocomida',
            name='id_tipoComida',
            field=models.AutoField(db_column='idTipoComida', default=1, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='tipocomida',
            name='tipo_comida',
            field=models.CharField(default='Broaster', max_length=20),
        ),
        migrations.AlterField(
            model_name='producto',
            name='nombre',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='producto',
            name='tipo_comida',
            field=models.ForeignKey(db_column='idTipoComida', on_delete=django.db.models.deletion.CASCADE, to='pedido.tipocomida'),
        ),
    ]
