# Generated by Django 4.1.2 on 2023-06-30 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0002_remove_producto_id_remove_tipocomida_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='tipo_comida',
            new_name='id_tipoComida',
        ),
        migrations.AlterField(
            model_name='producto',
            name='activo',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='tipocomida',
            name='id_tipoComida',
            field=models.AutoField(db_column='idTipoComida', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='tipocomida',
            name='tipo_comida',
            field=models.CharField(max_length=20),
        ),
    ]
