# Generated by Django 4.2.2 on 2023-06-21 01:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0002_remove_orden_cantidad_remove_orden_producto_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orden',
            name='cantidad',
        ),
        migrations.RemoveField(
            model_name='orden',
            name='producto',
        ),
    ]
